- .circleci/config.yml
- Pipfile
- elmo/connector.py
- elmo/router.py
- setup.py
- tests/test_base.py
- tox.ini
Related to #2
* Adds `pytest` and `tox` as testing framework and runner
* Adds `black` and `flake8` as linters and fromatters
* Adds support for CircleCI
> [dev/test] Add testing framework with CircleCI

- .circleci/config.yml
- README.md
Closes #2 
CircleCI configuration for `pytest` and `tox`.
> [dev/test] configure CircleCI

- .circleci/config.yml
- Pipfile
Closes #23 
Add `codecov` for test coverage.
> [dev/testing] add Codecov for code coverage

- README.md
- elmo/api/client.py
Closes #12 
Add instructions to use `ElmoClient`.
> [docs] add README with instructions to use the ElmoClient

- elmo/api/client.py
- elmo/api/exceptions.py
- tests/test_client.py
Avoid message duplication when a client exception is raised.
> Improve client exceptions

- .circleci/config.yml
- requirements/requirements-linting.txt
- requirements/requirements-testing.txt
- tox.ini
* Update dependencies
* Add Python 3.8 to the test matrix
> [package] update dependencies and Python 3.8 support

- LICENSE
- requirements/requirements-linting.txt
- requirements/requirements-testing.txt
* Updates `LICENSE` file
* Updates testing dependencies
> Update testing dependencies

- README.md
Closes #59 
Explains what is `secret-code`.
> [docs] Explain what is secret-code

- requirements/requirements-linting.txt
- requirements/requirements-testing.txt
Supersede https://github.com/palazzem/econnect-python/pull/69
* Update development dependencies.
> Updated development dependencies

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- Closes #83 
Includes GitHub templates for:
- Bug reporting
- Feature requests and, overall, new features discussions
- Discord link to join the channel
None.
None.
> tools(template): add GitHub templates for pull requests and issues

- CONTRIBUTING.md
- README.md
- Closes #82 
Include contribution guidelines to help the best we can people who want to start contributing to the project.
None.
Some steps in the contributing guidelines are not described (e.g. create the dev environment). After the project structure is updated, we'll fill all these gaps.
> docs: add Contribution Guidelines

- setup.py
> Bump version 0.4.0

- src/elmo/api/client.py
- src/elmo/api/exceptions.py
- src/elmo/devices.py
- src/elmo/utils.py
- tests/conftest.py
- tests/fixtures/responses.py
- tests/test_client.py
- tests/test_devices.py
- tests/test_utils.py
None.
This PR enhances the testing infrastructure by using a `client` fixture (see #96) that simulates the behavior of a real client. Additionally, we've addressed an incompatibility issue with this change. Key modifications in this PR include:
1. Implementation of the `client` fixture for more realistic testing without invoking the real client, or relying on mocks.
2. Refactoring of `AlarmDevice.update()` to leverage the new API. While initial tests passed, there were undetected operational issues that are now resolved.
3. `AlarmDevice` methods now log errors.
4. **Breaking Change**: The `AlarmDevice.connect()` method no longer invokes `update()`. This change streamlines the method's responsibility and simplifies the testing process, even though it initially appeared to be a beneficial …
> refactor!: `AlarmDevice` uses integration test client to ensure `update()` compatibility with the new API

- src/elmo/__about__.py
Releasing [milestone 0.5.0](https://github.com/palazzem/econnect-python/milestone/6?closed=1)
> release: version 0.5.0

- .github/workflows/testing.yaml
- README.md
n/a
Add GitHub actions badges to our docs, and enable Coveralls
n/a
n/a
> docs: add badges to README and enable code coverage reporting

- README.md
- pyproject.toml
- src/elmo/api/client.py
- tests/test_client.py
- tox.ini
n/a
Use `xml` exporter to align coveralls coverage with reality.
Check coveralls build.
n/a
> ci: write xml coverage report to support coveralls

- src/elmo/__about__.py
> release: build version 0.8.0

- src/elmo/api/client.py
- tests/test_client.py
Add functions to activate and deactivate outputs
> feat: add output command

- src/elmo/api/client.py
- Related to #143 
Add `DEBUG` logs to arm, disarm, lock and unlock responses to triage errors in case something doesn't work. It adds also the library version when the client is initialized.
n/a
n/a
> fix(log): debug log for arm/disarm/lock/unlock responses

- src/elmo/api/exceptions.py
- Follow-up for #147 
Simplify exception message.
n/a
n/a
> fix(log): simplify `DeviceDisconnectedError` error message
