Pipfile, elmo/conf/__init__.py, elmo/conf/base.py, elmo/conf/config.py, elmo/conf/exceptions.py, elmo/conf/options.py, elmo/conf/validators.py, tests/test_base.py, tests/test_config.py, tests/test_options.py, tests/test_validators.py, tox.ini
Closes #17 
Adds a `conf` module to define application settings. Each setting is defined with an `Option`  class that includes built-in validators and is extendable to add more. `Option` initialization exposes the following kwargs:
* `default`: to define the default value
* `allow_null`: if `None` value is allowed or not
* `validators`: a list of functions that are executed to validate option's value
```python
from elmo.conf.config import BaseConfig
class Settings(BaseConfig):
url = Option(default="http://example.com", allow_null=False)
home = Option()
dry_run = Option(validators=[is_boolean])
settings = Settings()
settings.is_valid()  # executes all options validators
```
=> [config] add configuration system to define application settings

Pipfile, tests/conftest.py, tests/test_client.py
Instead of having a complicated `conftest.py` that has an internal router to handle different responses, the project now uses [responses](https://github.com/getsentry/responses).
* the change doesn't alter the test suite
* every test mocks only the endpoint the test is calling
=> Use `responses` to mock requests instead of using a testing router

elmo/api/client.py, elmo/conf.py, tests/conftest.py
Decouple `ElmoClient` from `Settings`. Settings are now related to the base project (the web server / cloud function) that injects those values into the client.
=> Decouple ElmoClient from Settings

elmo/api/client.py, tests/test_client.py
When calling `Elmoclient.auth(username, password)`, the access token is returned to the caller. The access token is still cached in `_session_id` attribute.
=> [core/client] method auth() returns the access token

elmo/api/client.py, tests/test_client.py
Closes #34 
Provides an extra `kwarg` to the `ElmoClient` constructor, so that it's possible:
```python
from elmo.api.client import ElmoClient
c = ElmoClient(session_id="test)
```
=> [core/client] add session_id to the ElmoClient initializer

elmo/api/client.py, elmo/api/exceptions.py, tests/test_client.py
Closes #37 
Leverages requests `Response.raise_for_status()` call, so that it's not needed anymore to check the result and raise an internal exception. This removes all the duplication about error handling, and every `ElmoClient` method does only what it needs.
=> [core/client] leverage requests raise_for_status() instead of internal exceptions handling

elmo/api/client.py, elmo/api/router.py, elmo/utils/parser.py, elmo/utils/response_helper.py, setup.py, tests/conftest.py, tests/test_client.py, tests/test_utils.py, tox.ini
Closes #36 
Adds a new public method to `ElmoClient` to make calls to multiple pages and endpoints to retrieve the global status of the system. It retrieves:
* Armed/Disarmed areas: https://connect.elmospa.com/api/areas | POST | sessionId
* Inputs status: https://connect.elmospa.com/api/inputs | POST | sessionId
* Area names: https://connect.elmospa.com/vendor/Areas | GET | only cookies
* Entries names: https://connect.elmospa.com/vendor/Inputs | GET | only cookies
Calling the method returns a Python `dict` with the following data:
```python
{
"areas_armed": [{"id": 0, "name": "Entryway"}, ...],
"areas_disarmed": [{"id": 1, "name": "Kitchen"}, ...],
"inputs_alerted": [{"id": 0, "name": "Door"}, ...],
"inputs_wait": [{"id": 1, "name": "Window"}, ...],
}
assert len(status["inputs_alerted"]) …
```
=> Add `check()` API to retrieve the status of the system

elmo/api/client.py, tests/test_client.py
Follow-up of #44 
Extends `arm()` and `disarm()` public APIs, so that one or multiple sectors can be armed/disarmed. The API change is backward compatible because `sectors` is an optional kwarg.
```python
client.arm()        # Arm all sectors
client.arm([3, 4])  # Arm only sectors 3 and 4
client.disarm()     # Disarm all sectors
client.disarm([3])  # Disarm only sector 3
```
=> Extend Arm() and Disarm() to enable/disable one or multiple sectors

.gitignore, elmo/api/client.py, elmo/api/router.py, elmo/utils/parser.py, tests/test_client.py, tests/test_decorators.py, tests/test_utils.py
Follow-up of #44 
This PR introduces the Authentication API instead of using a form and parsing the `SessionID` from the web page. Introduced changes are:
* Uses `<base_url>/api/login` endpoint to grab the `session_id`
* A failed authentication raises `HTTPError` instead of `PermissionDenied`. `PermissionDenied` exception is used only when a `session_id` is not available
* Removes `get_access_token()`
=> Use Authentication API instead of scraping the SessionID

elmo/api/client.py, tests/test_client.py
When calling the `client.auth()` method, the `/api/login` endpoint may return a result with `Redirect: true`. In that case, we should follow the redirect and try to authenticate again.
=> Handle authentication redirects

elmo/api/client.py, tests/test_client.py
This PR makes the `client._query()` a public API. Now it's possible to query individual parts of the system as follows:
```python
from elmo import query
sectors_armed, sectors_disabled = client.query(query.SECTORS)
inputs_alerted, inputs_wait = client.query(query.INPUTS)
```
Client `check()` method is now considered a shortcut that returns a `dict` for the entire status of the system.
=> Make client.query() a public API

setup.py
Related to #42 
* Add `LICENSE` classifier
* Update package name to `econnect-python`
* Include Python 3.8 classifier
=> Update package name to econnect-python; add PyPI classifiers

README.md, elmo/api/client.py
Related to #42 
Improves the README to provide better instructions for the new API. It also renames the entire project to `econnect-python`.
=> Update README usage section

README.md, elmo/api/client.py, elmo/api/router.py, tests/conftest.py, tests/test_client.py
This change introduces a simpler constructor that has already the following defaults:
* base_url: `https://connect.elmospa.com`
* domain: `None`
To create a client it's enough to:
```python
c = ElmoClient()
c.auth("username", "password")
```
or:
```python
c = ElmoClient(base_url="https://connect3.elmospa.com, domain="nwd")
c.auth("username", "password")
```
This is not a breaking change and a regression test has been added.
In this change we also removed `vendor` as part of the API because it was meaningless. Now it has been renamed to `domain`.
=> ElmoClient constructor has now defaults

elmo/api/exceptions.py, elmo/api/router.py, tests/test_router.py
Closes #58 
By design, the client must not accept any URL that is not encrypted (HTTPS). If a non-HTTPS url is used, a `ValidationError` is raised to the main application.
There is no way to bypass this, so in case you _really_ need an `http` endpoint, feel free to [open a new issue](https://github.com/palazzem/econnect-python/issues) so we can discuss the requirement there. The main reason why I prefer this approach, is because such credentials are _really_ sensitive (they control your home alarm system) and so I'd prefer to prevent any possible typo/unwanted mistake.
```python
ElmoClient(base_url="http://example.com")     # Raises ValidationError exception
ElmoClient(base_url="https://example.com")    # Is accepted
```
=> Introduce a safer API so that only HTTPS urls can be used

elmo/api/client.py, elmo/api/decorators.py, elmo/api/exceptions.py, tests/conftest.py, tests/test_client.py, tests/test_decorators.py
When a new session is created, the stored `session_id` is a short-lived token with 10 minutes expiration (at the time of writing). With this change, after the token is retrieved via `client.auth()` API call but it's used later when it's not valid anymore, the `@required_session` decorator detects `401 HTTPError` exceptions and translates these in `InvalidToken` exceptions.
The caller should catch the exception and repeat the authentication via `client.auth()`.
```python
try:
client.arm()
except InvalidToken:
client.auth("test", "test")
```
=> Handle token expiration

elmo/api/client.py, elmo/api/decorators.py, elmo/api/exceptions.py, tests/test_client.py, tests/test_decorators.py
The previous version was relying only on `HTTPError` exception from the `requests` package. To make the code more generic and to raise meaningful exceptions, every method and decorator handles client/server errors.
The following exceptions have been added:
- `CredentialError`: when incorrect username/password are used
- `LockError`: when there is a race condition with another application, while trying to obtain the lock
- `CodeError`: when the used `code` is not correct
- `InvalidSector`: when using `arm()` or `disarm()`, an invalid sector is used
Cases that are covered are the following:
- Acquire the lock when it has been acquired already by someone else
- Incorrect username or password
- Incorrect code
- Call a method without obtaining the lock
- Call any method when a token is expired …
=> Improved Error Handling

elmo/api/client.py, tests/test_client.py
Closes #56 
With the previous behavior, any kind of exception raised in a `with client.lock(code):` block was preventing the `Lock()` from being released. The change ensures that `unlock()` is called in any case, behaving as a `try-finally` block.
=> [core/client] Ensure unlock() is called even if an exception is raised in the block

elmo/api/client.py, elmo/api/router.py, tests/test_client.py
Econnect API implements a long-polling in `/api/updates` endpoint. This change leverages this API to understand when the state is updated, so that it can trigger a `client.check()` call to get the latest. It prevents making a random polling (e.g. every 5 seconds), while triggering an update only when something changes.
At the time of writing, this API blocks the thread for 15 seconds, or unless something changes. To make it work, the client has to store inputs and areas IDs to get an update. This is not ideal but that's what the API offers.
=> Implement long-polling to retrieve state updates

README.md, elmo/api/client.py, tests/test_client.py
This change removes the `client.check()` API. The rationale is that this shortcut is considered a duplicate and violates the `ElmoClient` class responsibility. This class must stay lightweight without any extra logic other than handling the connection and make API calls.
=> Remove check() API

elmo/api/client.py, tests/conftest.py, tests/test_client.py
Follow-up of #71
Closes #57
Removes any filtering logic from `client.query()` API who will be implemented in another component to keep the connector lightweight. In this case, a `dict` with selected fields are returned, instead of returning multiple items. This simplifies the API that can be used as a building block for a more complex logic.
Returned dict has the following structure:
```python
{
"id": 1,
"index": 0,
"element": 3,
"excluded": False,
"name": "Kitchen",
}
```
This PR adds `excluded` field that can be used to retrieve system input exclusion status.
=> Refactor query() API so that a raw query (dict) is returned; add "excluded" field to returned dict

elmo/api/client.py, tests/test_client.py
- Updates `client.query()` API to return also a `last_id` that is needed to use the long-polling API (it will be used by another component).
- Items are grouped under `sectors` or `inputs` keys
Returned object has the following structure:
```python
{
"last_id": 4,
"sectors": {
0: {
"element": 1,
"id": 1,
"index": 0,
"excluded": False,
"name": "Living Room",
},
1: {
"element": 2,
"id": 2,
"index": 1,
"excluded": False,
"name": "Bedroom",
},
2: {
"element": 3,
"id": 3,
"index": 2,
"excluded": False,
"name": "Kitchen",
},
}
{
"last_id": 4,
"inputs": {
0: {
"element": 1,
"id": 1,
"index": 0,
"excluded": False,
"name": "Living Room",
},
1: {
"element": 2,
"id": 2,
"index": 1,
"excluded": False,
"name": "Bedroom",
},
2: {
"element": 3,
"id": 3,
"index": 2,
"excluded": False,
"name": "Kitchen", …
```
=> query() API returns also "last_id" field; items are grouped under "sectors" or "inputs" keys

README.md, pyproject.toml, tox.ini
- Closes #84 
Add support only for the following Python versions:
- 3.8
- 3.9
- 3.10
- 3.11
`tox` test matrix has been updated.
EOL versions have been dropped.
=> feat!: drop support for EOL Python versions; support Python 3.8 -> 3.11

pyproject.toml
n/a
Ensure the project is called `econnect-python` instead of `elmo` as it is the name of the python package in pypi.
n/a
n/a
=> package: ensure project name is econnect-python; pytest python PATH is `src`

.github/workflows/building.yaml, pyproject.toml, src/elmo/__about__.py
n/a
The latest release used `hatch` to build Python targets. Unfortunately the targets configuration was missing, and the entire project has been shipped as `src/elmo` without defining `elmo` as a package. This generates import errors in projects using this library.
This change now ships a Python package with the right `hatch` configuration.
"Building" GitHub actions now verifies if the package is built correctly.
n/a
=> fix(builder): update Hatch build target to include `elmo` package

README.md, src/elmo/api/router.py, src/elmo/systems.py, tests/test_client.py
- Closes #110 
Supports both Elmo e-Connect and IESS Metronet systems, by exposing their default URLS.
**Usage:**
```python
from elmo.api.client import ElmoClient
from elmo.systems import ELMO_E_CONNECT, IESS_METRONET
client = ElmoClient()
client = ElmoClient(base_url=ELMO_E_CONNECT)
client = ElmoClient(base_url=IESS_METRONET)
```
n/a
n/a
=> feat: support IESS Metronet system

src/elmo/api/client.py, tests/test_client.py
With this change we add the support for verify the last id in the alerts for polling updates
=> feat: add `last_id` for alerts poll

src/elmo/api/client.py, tests/test_client.py
Change how the system send the arm and the disarm request
With this method, we can arm and disarm multiple sectors by sending a single request
=> fix: arm and disarm multiple sectors with one request

src/elmo/api/client.py, tests/test_client.py
- Closes https://github.com/palazzem/ha-econnect-alarm/issues/115
This update refines the `query()` method in the client, which fetches synchronized data between the main unit and the cloud (using `_get_descriptions()` under the hood). Issues arise when strings are not in sync, specifically when:
1. The central unit has defined and `InUse` outputs, inputs, or sectors.
2. The cloud is not in sync, leading to missing keys (9, 10, or 12) in `_get_descriptions()`, causing a `KeyError`.
To address this, we've implemented a safer access via the dictionary `get()` method. Now, if a string is missing, `Unknown` is returned instead of an error.
Test with a central unit where an output is `InUse`, but no strings are configured in the cloud.
n/a
=> fix(client): prevent KeyError when inputs/outputs/sectors are not in sync with the cloud

src/elmo/api/client.py, src/elmo/api/exceptions.py, tests/test_client.py
- Closes [#112](https://github.com/palazzem/ha-econnect-alarm/issues/112)
Instead of raising multiple exceptions and assuming what the error is, we raise a single `CommandError` exception when any command fails. Furthermore, we log the actual backend response, if any.
n/a
n/a
=> fix(log)!: `Invalid*` exceptions replaced with `CommandError`; errors are logged with the API response

src/elmo/api/client.py, tests/test_client.py
- Closes #141 
Adds `user_id` optional parameter to `lock()`. This change adds support for all main units that require the `userId` parameter during the unit authentication.
n/a
n/a
=> feat: `lock()` accepts an optional `userId`

src/elmo/api/client.py, src/elmo/api/exceptions.py, tests/test_client.py
- Closes #146 
Raises a `DeviceDisconnectedError` if the main unit is disconnected.
Disconnect the unit and call the `client.query()`.
n/a
=> feat(api): handle main unit disconnections

.github/workflows/linting.yaml, .github/workflows/testing.yaml, tox.ini
- Closes #149 
Changes the test matrix to support the following Python versions:
- 3.8
- 3.9
- 3.10
- 3.11
- 3.12
Support of Python 3.12 has been added.
Run the testing matrix:
```bash
tox
```
n/a
=> feat: add support for Python 3.12

.pre-commit-config.yaml
n/a
Update all `pre-commit` hooks.
n/a
n/a
=> tools: update pre-commit hooks

src/elmo/api/client.py, tests/test_client.py
- Fix #154 
This change removes the assumption that items ID returned from the Cloud API, are ordered.
Home Assistant integration polling should work again.
n/a
=> fix(client): determine the `last_id` by finding the maximum `Id` in the list

src/elmo/api/client.py, tests/test_client.py
- Fixes #158 
This change sets `Origin` and `Referer` headers during client initialization. The change is required otherwise polling will not work.
n/a
n/a
=> fix(api): set `Referer` and `Origin` headers to make polling work

src/elmo/api/client.py, src/elmo/utils.py, tests/fixtures/responses.py, tests/scripts/debug_polling.py, tests/test_client.py, tests/test_utils.py
- Fixes #158 
This change (re)introduces the web page login when e-Connect alarm system is used. This is required as it seems the public API doesn't register the client to get updates from the long-polling API.
We introduce also `tests/scripts/debug_polling.py` debug script to verify if long-polling is working or not in a real world scenario.
Use `tests/scripts/debug_polling.py` to see if long polling works in your scenario.
This is a temporary change as it looks like Elmo is making updates to the Cloud API. As soon as a new public and documented API is out, we'll probably drop this approach in favor of something more reliable.
=> fix(api): use web login for e-Connect to register the client for long-polling

.github/workflows/building.yaml, .github/workflows/linting.yaml, .github/workflows/testing.yaml, pyproject.toml, tox.ini
n/a
This change drops support for Python 3.8 and extends support for Python 3.9 -> 3.13. In this PR we also update GitHub runner OS versions to `ubuntu-24.04` as the previous one is now unsupported (see: https://github.com/palazzem/econnect-python/actions/runs/14539342374)
n/a
n/a
=> feat(python)!: support Python 3.9 -> 3.13

src/elmo/api/client.py, tests/test_client.py
- Fixes #158 for a specific session token handling scenario.
This PR ensures the client consistently uses the `SessionID` obtained during the web login flow, regardless of whether a `redirect_url` is provided by the e-Connect Cloud API. 
**Background:**  
Previously, if a `redirect_url` was specified, the client would default to the session information derived from that redirect, leading to a situation where updates stopped being received after the first access token expired (typically within 10–20 minutes). This change addresses that problem by enforcing the use of the `SessionID` retrieved using the web login, thus maintaining a valid session that receives updates from the Cloud API.
**How It Works:**
Overrides the behavior when a `redirect_url` is returned, so that the session …
=> fix(api): use `weblogin` access token with API base_url redirect

src/elmo/api/client.py, src/elmo/systems.py, tests/test_client.py
- https://github.com/palazzem/ha-econnect-alarm/issues/186
This change retrieves the session ID using the web login form for both e-Connect and Metronet. Without this change, client session is not registered for long-polling updates.
n/a
If e-Connect or Metronet `base_url` are not used, we disable the web login. This is an edge case that probably will never happen, but at least we don't introduce a breaking change.
=> fix(client): use web login also for IESS
